module.exports = {
  CREATE_IN_PROGRESS: "CREATE_IN_PROGRESS",
  CREATE_FAILED: "CREATE_FAILED",
  CREATE_COMPLETE: "CREATE_COMPLETE",
  DELETE_IN_PROGRESS: "DELETE_IN_PROGRESS",
  DELETE_FAILED: "DELETE_FAILED",
  DELETE_COMPLETE: "DELETE_COMPLETE",
  DELETE_SKIPPED: "DELETE_SKIPPED",
  UPDATE_IN_PROGRESS: "UPDATE_IN_PROGRESS",
  UPDATE_FAILED: "UPDATE_FAILED",
  UPDATE_COMPLETE: "UPDATE_COMPLETE",
  ROLLBACK_IN_PROGRESS: "ROLLBACK_IN_PROGRESS",
  ROLLBACK_COMPLETE: "ROLLBACK_COMPLETE",
  NOT_FOUND: "NOT_FOUND"
};
